### ISSUE TITLE
Dataset collection

### ISSUE THREAD

**Issue by marcoruizrueda-ist** [karimelhage/methane-leak-detection-in-satellite-imagery#1]
Hi, thanks for the code and nice explanation. Could you please explain how you collected this satellite images with and without methane? Also, from which satellite?
Regards

**Comment by karimelhage** [comment]
Hi Marco, 

Thanks for your question. The dataset was provided by the company hosting the hackathon. The exact nature of the data collection and source was not revealed to us however we were told that it was open source.

Best Regards,
Karim
